### PR TITLE
Celer Network gnark sha256. Less constraints.

### PR DESCRIPTION
**Pull request by liuxiaobleach**
Celer Network. Zk gnark sha-256, which has less constraints.
More detail:
https://github.com/celer-network/zk-benchmark/tree/main/gnark.

### CODE REVIEW

**Review by jplaui — COMMENTED** [review]
Hi @tumberger, I would have the following comments:
- @tumberger should/can the update support the latest gnark-crypto version 0.10.0? if so, you could create a review -> request changes for requesting another commit which addresses the requirement.
- what about copyright licensing @tumberger? you could add a license file per folder (e.g. prf/sha256 with a license.txt which indicates a copyright notice per contribution) to indicate the copyright notice per accepted commit/pull request. I would suggest adding a first license file which contains the initial copyright notice, then updates could add the copyright claims  into the same file which would produce a verifiable change log.
- clean up of commenting out old implementation @liuxiaobleach. @tumberger maybe you could add a review -> request changes to require such a commit before merging the pull request 
Apart from that, the changes look good.

**Review by tumberger — CHANGES_REQUESTED** [review]
- [x] Remove commented code / previous SHA-256 version

**Comment by liuxiaobleach** [comment]
> * [ ]  Remove commented code / previous SHA-256 version

Done

**Comment by liuxiaobleach** [comment]
> Hi @tumberger, I would have the following comments:
> 
> * @tumberger should/can the update support the latest gnark-crypto version 0.10.0? if so, you could create a review -> request changes for requesting another commit which addresses the requirement.
> * what about copyright licensing @tumberger? you could add a license file per folder (e.g. prf/sha256 with a license.txt which indicates a copyright notice per contribution) to indicate the copyright notice per accepted commit/pull request. I would suggest adding a first license file which contains the initial copyright notice, then updates could add the copyright claims  into the same file which would produce a verifiable change log.
> * clean up of commenting out old implementation @liuxiaobleach. @tumberger maybe you could add a review -> request changes to require such a commit before merging the pull request
>   Apart from that, the changes look good.

(1) gnark 0.8.0 only support gnark-crypto 0.9.1 now. I think current config make sense.
https://github.com/ConsenSys/gnark/blob/2753ae60ed8f6de4fc793d4ec3cbcb9291d52236/go.mod#L8
(2) a simple lisence file is added. BTW, celer sha256 is free to use now, just same in our public repo, which has more lower constraints.
https://github.com/celer-network/brevis-circuits/tree/main/gadgets/sha256

**Review by tumberger — APPROVED** [review]

**Pull request merged**
